import type { Metadata, Viewport } from "next";
import { Cormorant_Garamond, Inter, Caveat } from "next/font/google";
import "./globals.css";
import { PROJECTS, SITE } from "@/lib/data";

const display = Cormorant_Garamond({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const body = Inter({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

const script = Caveat({
  variable: "--font-script",
  subsets: ["latin"],
  weight: ["500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: "Somesh M | AI Developer & Full Stack Engineer",
    template: "%s · Somesh M",
  },
  description:
    "Somesh M is an AI Developer and Full Stack Engineer building intelligent systems using Python, React, Machine Learning, Generative AI, and RAG.",
  keywords: [
    "Somesh M",
    "Somesh M developer",
    "Somesh M AI developer",
    "Somesh M full stack engineer",
    "Somesh M portfolio",
    "Somesh M software engineer",
    "Somesh M India",
    "AI Developer",
    "Full Stack Engineer",
    "Computer Science student",
    "RAG systems",
    "Generative AI",
    "Intelligent software systems",
  ],
  authors: [{ name: "Somesh M", url: SITE.url }],
  creator: "Somesh M",
  publisher: "Somesh M",
  alternates: { canonical: SITE.url },
  applicationName: "Somesh M Portfolio",
  verification: {
    google: "googleaee54bf2d5a00ed1",
  },
  openGraph: {
    type: "website",
    url: SITE.url,
    locale: "en_US",
    siteName: "Somesh M — Portfolio",
    title: "Somesh M | AI Developer & Full Stack Engineer",
    description:
      "Somesh M is an AI Developer and Full Stack Engineer building intelligent systems using Python, React, Machine Learning, Generative AI, and RAG.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Somesh M | AI Developer & Full Stack Engineer",
    description:
      "Somesh M is an AI Developer and Full Stack Engineer building intelligent systems using Python, React, Machine Learning, Generative AI, and RAG.",
    // route generated by app/opengraph-image.tsx (served as image/png)
    images: [`${SITE.url}opengraph-image`],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "portfolio",
};

export const viewport: Viewport = {
  themeColor: "#F3EDE2",
  width: "device-width",
  initialScale: 1,
};

const projectList = PROJECTS.map((p, i) => {
  const repo = p.links.find((l) => l.href.includes("github.com"))?.href;
  return {
    "@type": "ListItem",
    position: i + 1,
    item: {
      "@type": "SoftwareSourceCode",
      name: p.name,
      description: `${p.tagline} ${p.description}`,
      ...(repo ? { codeRepository: repo } : {}),
      programmingLanguage: p.stack,
    },
  };
});

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": `${SITE.url}#person`,
      name: "Somesh M",
      url: SITE.url,
      image: `${SITE.url}opengraph-image`,
      jobTitle: "AI Developer, Full Stack Engineer",
      description:
        "Computer Science & Business Systems student, AI developer and full stack engineer building AI-powered intelligent software systems.",
      address: {
        "@type": "PostalAddress",
        addressCountry: "IN",
      },
      knowsAbout: [
        "Artificial Intelligence",
        "Machine Learning",
        "Generative AI",
        "RAG systems",
        "Full-stack development",
        "Cybersecurity",
        "React",
        "Python",
        "Flutter",
      ],
      sameAs: [SITE.github, SITE.linkedin, SITE.leetcode, SITE.hackerrank],
      alumniof: [
        {
          "@type": "Organization",
          name: "Brainery Spot Technologies",
        },
        {
          "@type": "Organization",
          name: "Nandha Info Tech",
        },
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE.url}#website`,
      name: "Somesh M — Portfolio",
      url: SITE.url,
      inLanguage: "en",
      publisher: {
        "@id": `${SITE.url}#person`,
      },
    },
    {
      "@type": "ProfilePage",
      "@id": `${SITE.url}#profile`,
      url: SITE.url,
      name: "Somesh M | AI Developer & Full Stack Engineer",
      inLanguage: "en",
      mainEntity: {
        "@id": `${SITE.url}#person`,
      },
    },
    {
      "@type": "ItemList",
      name: "Selected work by Somesh M",
      itemListElement: projectList,
    },
  ],
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${body.variable} ${script.variable} h-full`}
    >
      <body className="min-h-full bg-cream text-choco antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-sm focus:bg-choco focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-cream"
        >
          Skip to content
        </a>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <noscript>
          <style>{`.reveal{opacity:1!important;transform:none!important}`}</style>
        </noscript>
        {children}
      </body>
    </html>
  );
}
