import type { Metadata, Viewport } from "next";
import { Cormorant_Garamond, Inter, Caveat } from "next/font/google";
import "./globals.css";
import { PROJECTS, SITE } from "@/lib/data";

const display = Cormorant_Garamond({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const body = Inter({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

const script = Caveat({
  variable: "--font-script",
  subsets: ["latin"],
  weight: ["500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: "Somesh M | AI Developer & Full Stack Engineer Portfolio",
    template: "%s · Somesh M",
  },
  description:
    "Somesh M - AI Developer and Full Stack Engineer specializing in Machine Learning, Generative AI, RAG systems, Python, React, and Flutter. Portfolio showcasing intelligent software systems, ML projects, and full-stack applications.",
  keywords: [
    "Somesh M",
    "Somesh M portfolio",
    "Somesh M developer",
    "Somesh M AI developer",
    "Somesh M full stack engineer",
    "Somesh M software engineer",
    "Somesh M machine learning",
    "Somesh M India",
    "Somesh M projects",
    "Somesh M github",
    "AI Developer portfolio",
    "Full Stack Engineer portfolio",
    "Machine Learning developer",
    "Python developer portfolio",
    "React developer portfolio",
    "Flutter developer",
    "Generative AI developer",
    "RAG systems developer",
    "AI portfolio India",
    "Software engineer portfolio",
    "Computer Science portfolio",
    "Intelligent software systems",
    "AI projects portfolio",
    "ML projects portfolio",
  ],
  authors: [{ name: "Somesh M", url: SITE.url }],
  creator: "Somesh M",
  publisher: "Somesh M",
  alternates: { canonical: SITE.url },
  applicationName: "Somesh M Portfolio",
  verification: {
    google: "googleaee54bf2d5a00ed1",
  },
  openGraph: {
    type: "website",
    url: SITE.url,
    locale: "en_US",
    siteName: "Somesh M Portfolio",
    title: "Somesh M | AI Developer & Full Stack Engineer Portfolio",
    description:
      "Somesh M - AI Developer and Full Stack Engineer specializing in Machine Learning, Generative AI, RAG systems, Python, React, and Flutter. Portfolio showcasing intelligent software systems and ML projects.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Somesh M | AI Developer & Full Stack Engineer Portfolio",
    description:
      "Somesh M - AI Developer and Full Stack Engineer specializing in Machine Learning, Generative AI, RAG systems, Python, React, and Flutter.",
    // route generated by app/opengraph-image.tsx (served as image/png)
    images: [`${SITE.url}opengraph-image`],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "portfolio",
};

export const viewport: Viewport = {
  themeColor: "#F3EDE2",
  width: "device-width",
  initialScale: 1,
};

const projectList = PROJECTS.map((p, i) => {
  const repo = p.links.find((l) => l.href.includes("github.com"))?.href;
  return {
    "@type": "ListItem",
    position: i + 1,
    item: {
      "@type": "SoftwareSourceCode",
      name: p.name,
      description: `${p.tagline} ${p.description}`,
      ...(repo ? { codeRepository: repo } : {}),
      programmingLanguage: p.stack,
    },
  };
});

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": `${SITE.url}#person`,
      name: "Somesh M",
      alternateName: ["Somesh", "Somesh M Developer"],
      url: SITE.url,
      image: `${SITE.url}opengraph-image`,
      jobTitle: "AI Developer, Full Stack Engineer",
      description:
        "Somesh M is a Computer Science & Business Systems student, AI developer and full stack engineer specializing in building AI-powered intelligent software systems using Machine Learning, Generative AI, RAG systems, Python, React, and Flutter.",
      address: {
        "@type": "PostalAddress",
        addressCountry: "IN",
      },
      knowsAbout: [
        "Artificial Intelligence",
        "Machine Learning",
        "Generative AI",
        "RAG systems",
        "Full-stack development",
        "Cybersecurity",
        "React",
        "Python",
        "Flutter",
        "TypeScript",
        "JavaScript",
        "Dart",
        "AI Development",
        "Software Engineering",
      ],
      sameAs: [SITE.github, SITE.linkedin, SITE.leetcode, SITE.hackerrank],
      alumniof: [
        {
          "@type": "Organization",
          name: "Brainery Spot Technologies",
        },
        {
          "@type": "Organization",
          name: "Nandha Info Tech",
        },
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE.url}#website`,
      name: "Somesh M Portfolio",
      alternateName: "Somesh M - AI Developer Portfolio",
      url: SITE.url,
      inLanguage: "en",
      description: "Portfolio of Somesh M showcasing AI development, machine learning, and full stack engineering projects",
      publisher: {
        "@id": `${SITE.url}#person`,
      },
    },
    {
      "@type": "ProfilePage",
      "@id": `${SITE.url}#profile`,
      url: SITE.url,
      name: "Somesh M | AI Developer & Full Stack Engineer Portfolio",
      description: "Portfolio showcasing AI development, machine learning, and full stack engineering projects by Somesh M",
      inLanguage: "en",
      mainEntity: {
        "@id": `${SITE.url}#person`,
      },
    },
    {
      "@type": "ItemList",
      name: "Selected work by Somesh M",
      itemListElement: projectList,
    },
  ],
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${body.variable} ${script.variable} h-full`}
    >
      <body className="min-h-full bg-cream text-choco antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-sm focus:bg-choco focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-cream"
        >
          Skip to content
        </a>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <noscript>
          <style>{`.reveal{opacity:1!important;transform:none!important}`}</style>
        </noscript>
        {children}
      </body>
    </html>
  );
}
